### ISSUE TITLE
Country codes not fully ISO3166 compatible

### ISSUE THREAD

**Issue by saibotd** [easybill/php-sdk#5]
Hi, I'm using this API and noticed the following Error popping up every now an then:
`
[2018-11-16 21:23:46] app.CRITICAL: An exception occurred. {"exception":"[object] (easybill\\SDK\\Exception\\ModelDataNotValid(code: 3): country at /vendor/easybill/php-sdk/easybill/SDK/Client.php:672, SoapFault(code: 0): Data field incorrect at /vendor/easybill/php-sdk/easybill/SDK/Client.php:626)"} []
`
Sadly I don't know which country code triggers the error, but I'm using the ISO codes from a lib (https://github.com/mledoze/countries) which seems pretty accurate.

**Comment by saibotd** [comment]
The issue could be related to Finland (FI)

**Comment by timglabisch** [comment]
@saibotd FI is mapped to Finland so it should be fine. May it's related to `GB`(we expect `UK` here)?
I am going to close the issue here because it's not really related to the sdk, it's related to the easybill api.  I will create an internal ticket, in which we discuss and check the support of such a standard.

by the way, the error looks like you're using the soap api? please update and use the rest api :)

**Comment by saibotd** [comment]
Thanks! You could make it a bit clearer that the SOAP-Client is deprecated.

> Switch SDK to REST API under development!
> Note: v2 is not compatible with v1!

Doesn't really convey "**don't use this!**" for an outsider.
